version: '3.8'  # Указывается версия Docker Compose

services:
  doctors-appointment-notifier:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/doctors-appointment-notifier
    ports:
      - "2444:2444"
    restart: unless-stopped
